# Generated by Django 4.2.4 on 2024-06-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modalidad', models.CharField(choices=[('OL', 'Online'), ('PR', 'Presencial')], default='PR', max_length=2, verbose_name='Modalidad')),
                ('entrenadores', models.ManyToManyField(related_name='Modalidades', to='Entrenadores.entrenador')),
            ],
        ),
    ]
