# Generated by Django 4.2.4 on 2024-06-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenadores', '0003_alter_modalidad_nombre_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamiento',
            name='name',
            field=models.CharField(choices=[('MA', 'Mancuernas'), ('BA', 'Barra'), ('MQ', 'Maquinas')], default='N/A', max_length=3, verbose_name='Equipamiento disponible'),
        ),
    ]
