# Generated by Django 4.2.4 on 2024-06-12 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenadores', '0004_alter_equipamiento_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=40, verbose_name='Cargo del entrenador')),
                ('anos_exp', models.CharField(max_length=40, verbose_name='Años de experiencia')),
                ('desc', models.TextField(verbose_name='Descripción de la experiencia')),
                ('rut_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenadores.entrenador', verbose_name='Rut del entrenador')),
            ],
        ),
    ]
