# Generated by Django 4.2.4 on 2024-06-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenadores', '0005_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='ano_egreso',
            field=models.IntegerField(default=2024, verbose_name='Año de egreso'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='anos_exp',
            field=models.IntegerField(default=1, verbose_name='Años de experiencia'),
        ),
    ]
