# Generated by Django 4.2.4 on 2024-07-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenadores', '0006_educacion_ano_egreso_alter_experiencia_anos_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgEntr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_entr', models.ImageField(upload_to='')),
                ('rut_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenadores.entrenador', verbose_name='Rut del entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='AvatarEntr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('rut_en', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Entrenadores.entrenador', verbose_name='Rut del entrenador')),
            ],
        ),
    ]
