# Generated by Django 4.2.4 on 2024-07-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenadores', '0007_imgentr_avatarentr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarentr',
            name='avatar',
            field=models.ImageField(upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='imgentr',
            name='img_entr',
            field=models.ImageField(upload_to='avatars'),
        ),
    ]
