# Generated by Django 4.2.4 on 2024-07-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenadores', '0008_alter_avatarentr_avatar_alter_imgentr_img_entr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarentr',
            name='avatar',
            field=models.ImageField(upload_to='avatars', verbose_name='Avatar del entrenador'),
        ),
        migrations.AlterField(
            model_name='imgentr',
            name='img_entr',
            field=models.ImageField(upload_to='avatars', verbose_name='Imagen del entrenador'),
        ),
    ]
